-- ================================================================
-- EAGLES GEAR SOLUTIONS - BASE DE DATOS DE ALUMNOS
-- Proyecto: Campus Seminario Empresarial
-- Plataforma: Supabase / PostgreSQL
--
-- INSTRUCCIONES:
-- 1. Crea un proyecto nuevo en Supabase.
-- 2. Abre SQL Editor -> New query.
-- 3. Pega todo este archivo y presiona Run.
-- 4. Después crea las cuentas desde Authentication -> Users.
--
-- Este script se puede ejecutar nuevamente sin duplicar información.
-- ================================================================

-- 1. PERFIL DE CADA ALUMNO
create table if not exists public.student_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  phone text,
  company_name text,
  crm_customer_id bigint,
  city text,
  state text,
  country text default 'México',
  role text not null default 'student'
    check (role in ('admin', 'student')),
  status text not null default 'active'
    check (status in ('active', 'inactive', 'blocked')),
  must_change_password boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Compatibilidad por si se ejecuta sobre una versión anterior del esquema.
alter table public.student_profiles
  add column if not exists role text not null default 'student';

alter table public.student_profiles
  add column if not exists must_change_password boolean not null default true;

alter table public.student_profiles
  add column if not exists crm_customer_id bigint;

create unique index if not exists student_profiles_crm_customer_unique
  on public.student_profiles (crm_customer_id)
  where crm_customer_id is not null;

-- 2. CATÁLOGO DE CURSOS
create table if not exists public.courses (
  id text primary key,
  title text not null,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Curso inicial utilizado por la plataforma.
insert into public.courses (id, title, description, active)
values (
  'seminario-empresarial',
  'Seminario Empresarial',
  'De técnico a dueño: construye una empresa ordenada, rentable y con dirección.',
  true
)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  active = excluded.active,
  updated_at = now();

-- 3. INSCRIPCIONES
create table if not exists public.course_enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null references public.courses(id) on delete cascade,
  status text not null default 'active'
    check (status in ('active', 'completed', 'expired', 'cancelled')),
  enrolled_at timestamptz not null default now(),
  expires_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, course_id)
);

-- 4. PROGRESO DE LAS LECCIONES
create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null references public.courses(id) on delete cascade,
  lesson_id text not null,
  completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, course_id, lesson_id)
);

-- 5. ÍNDICES PARA CONSULTAS RÁPIDAS
create index if not exists student_profiles_status_idx
  on public.student_profiles (status);

create index if not exists student_profiles_role_idx
  on public.student_profiles (role);

create index if not exists course_enrollments_user_idx
  on public.course_enrollments (user_id);

create index if not exists course_enrollments_course_status_idx
  on public.course_enrollments (course_id, status);

create index if not exists lesson_progress_user_course_idx
  on public.lesson_progress (user_id, course_id);

-- 6. ACTUALIZACIÓN AUTOMÁTICA DE updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_student_profiles_updated_at on public.student_profiles;
create trigger set_student_profiles_updated_at
before update on public.student_profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_courses_updated_at on public.courses;
create trigger set_courses_updated_at
before update on public.courses
for each row execute function public.set_updated_at();

drop trigger if exists set_course_enrollments_updated_at on public.course_enrollments;
create trigger set_course_enrollments_updated_at
before update on public.course_enrollments
for each row execute function public.set_updated_at();

drop trigger if exists set_lesson_progress_updated_at on public.lesson_progress;
create trigger set_lesson_progress_updated_at
before update on public.lesson_progress
for each row execute function public.set_updated_at();

-- 7. AL CREAR UN USUARIO:
--    - crea su perfil;
--    - la inscripción se asigna explícitamente desde el panel o una integración.
create or replace function public.handle_new_student()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.student_profiles (
    id,
    email,
    full_name,
    phone,
    company_name
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'company_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_create_student on auth.users;
create trigger on_auth_user_created_create_student
after insert on auth.users
for each row execute function public.handle_new_student();

-- Si ya existían usuarios antes de correr este script, también los agrega.
insert into public.student_profiles (id, email, full_name)
select
  id,
  email,
  coalesce(raw_user_meta_data ->> 'full_name', '')
from auth.users
on conflict (id) do nothing;

-- Las inscripciones no se crean en bloque: así una cuenta solo ve los cursos
-- que realmente compró o que un administrador le asignó.

-- 7.1. RELACIÓN IDEMPOTENTE CON SISTEMAS EXTERNOS (CRM, checkout, etc.)
create table if not exists public.external_enrollments (
  id bigint generated by default as identity primary key,
  source text not null,
  external_id text not null,
  course_id text not null references public.courses(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  username text,
  status text not null default 'provisioning'
    check (status in ('provisioning', 'active', 'failed', 'revoked')),
  metadata jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, external_id, course_id)
);

create index if not exists external_enrollments_user_idx
  on public.external_enrollments (user_id);

drop trigger if exists set_external_enrollments_updated_at on public.external_enrollments;
create trigger set_external_enrollments_updated_at
before update on public.external_enrollments
for each row execute function public.set_updated_at();

-- 8. SEGURIDAD POR USUARIO (ROW LEVEL SECURITY)
alter table public.student_profiles enable row level security;
alter table public.courses enable row level security;
alter table public.course_enrollments enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.external_enrollments enable row level security;

-- Función segura para comprobar el rol sin provocar recursión en las políticas.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.student_profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'active'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.student_profiles
    where id = auth.uid()
      and status = 'active'
  );
$$;

revoke all on function public.is_active_user() from public;
grant execute on function public.is_active_user() to authenticated;

-- El alumno confirma el cambio de su contraseña desde una sesión autenticada.
-- La contraseña nunca se guarda en esta tabla; solamente se registra que completó el paso.
create or replace function public.mark_password_changed()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.student_profiles
  set must_change_password = false,
      updated_at = now()
  where id = auth.uid();
end;
$$;

revoke all on function public.mark_password_changed() from public;
revoke all on function public.mark_password_changed() from anon;
grant execute on function public.mark_password_changed() to authenticated;

-- Perfiles: cada alumno ve y actualiza solamente su perfil.
drop policy if exists "Students can view their own profile" on public.student_profiles;
create policy "Students can view their own profile"
on public.student_profiles for select
to authenticated
using (auth.uid() = id or public.is_admin());

drop policy if exists "Students can update their own profile" on public.student_profiles;
create policy "Students can update their own profile"
on public.student_profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Cursos: los usuarios registrados pueden consultar cursos activos.
drop policy if exists "Authenticated users can view active courses" on public.courses;
create policy "Authenticated users can view active courses"
on public.courses for select
to authenticated
using (active = true and public.is_active_user());

-- Inscripciones: cada alumno ve solamente las suyas.
drop policy if exists "Students can view their own enrollments" on public.course_enrollments;
create policy "Students can view their own enrollments"
on public.course_enrollments for select
to authenticated
using ((auth.uid() = user_id and public.is_active_user()) or public.is_admin());

-- Progreso: solamente el alumno dueño del registro puede verlo o modificarlo,
-- y únicamente mientras tenga una inscripción activa o completada.
drop policy if exists "Students can view their own progress" on public.lesson_progress;
create policy "Students can view their own progress"
on public.lesson_progress for select
to authenticated
using ((auth.uid() = user_id and public.is_active_user()) or public.is_admin());

drop policy if exists "Students can create their own progress" on public.lesson_progress;
create policy "Students can create their own progress"
on public.lesson_progress for insert
to authenticated
with check (
  auth.uid() = user_id
  and public.is_active_user()
  and exists (
    select 1
    from public.course_enrollments enrollment
    where enrollment.user_id = auth.uid()
      and enrollment.course_id = lesson_progress.course_id
      and enrollment.status in ('active', 'completed')
      and (enrollment.expires_at is null or enrollment.expires_at > now())
  )
);

drop policy if exists "Students can update their own progress" on public.lesson_progress;
create policy "Students can update their own progress"
on public.lesson_progress for update
to authenticated
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and public.is_active_user()
  and exists (
    select 1
    from public.course_enrollments enrollment
    where enrollment.user_id = auth.uid()
      and enrollment.course_id = lesson_progress.course_id
      and enrollment.status in ('active', 'completed')
      and (enrollment.expires_at is null or enrollment.expires_at > now())
  )
);

-- 9. PERMISOS BÁSICOS PARA USUARIOS AUTENTICADOS
grant usage on schema public to authenticated;
grant select on public.student_profiles to authenticated;
grant update (full_name, phone, company_name, city, state, country)
  on public.student_profiles to authenticated;
grant select on public.courses to authenticated;
grant select on public.course_enrollments to authenticated;
grant select, insert, update on public.lesson_progress to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Las funciones privadas de Vercel utilizan service_role para administrar
-- cuentas. Esta clave nunca debe colocarse en variables que empiecen con VITE_.
grant all privileges on public.student_profiles to service_role;
grant all privileges on public.courses to service_role;
grant all privileges on public.course_enrollments to service_role;
grant all privileges on public.lesson_progress to service_role;
grant all privileges on public.external_enrollments to service_role;
grant usage, select on all sequences in schema public to service_role;

-- ================================================================
-- LISTO.
-- Al crear un alumno en Authentication -> Users, se generarán
-- automáticamente su perfil. La inscripción se asigna desde el panel
-- administrativo o desde una integración autorizada.
--
-- PARA CREAR EL PRIMER ADMINISTRADOR:
-- 1. Crea primero su usuario en Authentication -> Users.
-- 2. Ejecuta esta instrucción por separado, cambiando el correo:
--
-- update public.student_profiles
-- set role = 'admin', status = 'active', must_change_password = false
-- where email = 'TU-CORREO-DE-ADMIN@EJEMPLO.COM';
-- ================================================================
