-- ============================================================================
-- EAGLES CAMPUS - MIGRACIÓN PARA INTEGRACIÓN CON EL CRM
-- Ejecutar una sola vez en el SQL Editor del proyecto Supabase DEL CAMPUS.
-- Es segura para los alumnos e inscripciones que ya existen.
-- ============================================================================

-- 1. Ya no inscribir automáticamente a toda cuenta nueva.
-- El panel administrativo y la integración asignarán el curso correcto.
create or replace function public.handle_new_student()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.student_profiles (
    id,
    email,
    full_name,
    phone,
    company_name
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'company_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

-- 1.1. El ID pertenece al Supabase del CRM. No es una llave foránea porque
-- ambos proyectos están separados, pero debe ser único en el Campus.
alter table public.student_profiles
  add column if not exists crm_customer_id bigint;

create unique index if not exists student_profiles_crm_customer_unique
  on public.student_profiles (crm_customer_id)
  where crm_customer_id is not null;

-- 2. Guardar la relación CRM -> alumno de forma idempotente.
create table if not exists public.external_enrollments (
  id bigint generated by default as identity primary key,
  source text not null,
  external_id text not null,
  course_id text not null references public.courses(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  username text,
  status text not null default 'provisioning'
    check (status in ('provisioning', 'active', 'failed', 'revoked')),
  metadata jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, external_id, course_id)
);

create index if not exists external_enrollments_user_idx
  on public.external_enrollments (user_id);

drop trigger if exists set_external_enrollments_updated_at on public.external_enrollments;
create trigger set_external_enrollments_updated_at
before update on public.external_enrollments
for each row execute function public.set_updated_at();

alter table public.external_enrollments enable row level security;

-- Esta tabla solamente la administran funciones privadas con service_role.
revoke all on public.external_enrollments from anon, authenticated;
grant all privileges on public.external_enrollments to service_role;
grant usage, select on all sequences in schema public to service_role;

-- No se eliminan inscripciones existentes.
-- ============================================================================
-- LISTO: ahora configura CAMPUS_PROVISIONING_SECRET en Vercel.
-- ============================================================================
